[package]
name = "my-smt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2 = {path = "./plonky2/plonky2"}
rand = "0.8.1"